# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/egp/vktest/Project/Astroworks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/egp/vktest/Project/Astroworks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egp/vktest/Project/Astroworks/CMakeFiles /home/egp/vktest/Project/Astroworks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egp/vktest/Project/Astroworks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Astroworks

# Build rule for target.
Astroworks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Astroworks
.PHONY : Astroworks

# fast build rule for target.
Astroworks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/build
.PHONY : Astroworks/fast

Source/Actor/Actor.o: Source/Actor/Actor.cpp.o
.PHONY : Source/Actor/Actor.o

# target to build an object file
Source/Actor/Actor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Actor.cpp.o
.PHONY : Source/Actor/Actor.cpp.o

Source/Actor/Actor.i: Source/Actor/Actor.cpp.i
.PHONY : Source/Actor/Actor.i

# target to preprocess a source file
Source/Actor/Actor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Actor.cpp.i
.PHONY : Source/Actor/Actor.cpp.i

Source/Actor/Actor.s: Source/Actor/Actor.cpp.s
.PHONY : Source/Actor/Actor.s

# target to generate assembly for a file
Source/Actor/Actor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Actor.cpp.s
.PHONY : Source/Actor/Actor.cpp.s

Source/Actor/Alien.o: Source/Actor/Alien.cpp.o
.PHONY : Source/Actor/Alien.o

# target to build an object file
Source/Actor/Alien.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Alien.cpp.o
.PHONY : Source/Actor/Alien.cpp.o

Source/Actor/Alien.i: Source/Actor/Alien.cpp.i
.PHONY : Source/Actor/Alien.i

# target to preprocess a source file
Source/Actor/Alien.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Alien.cpp.i
.PHONY : Source/Actor/Alien.cpp.i

Source/Actor/Alien.s: Source/Actor/Alien.cpp.s
.PHONY : Source/Actor/Alien.s

# target to generate assembly for a file
Source/Actor/Alien.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Alien.cpp.s
.PHONY : Source/Actor/Alien.cpp.s

Source/Actor/Building.o: Source/Actor/Building.cpp.o
.PHONY : Source/Actor/Building.o

# target to build an object file
Source/Actor/Building.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Building.cpp.o
.PHONY : Source/Actor/Building.cpp.o

Source/Actor/Building.i: Source/Actor/Building.cpp.i
.PHONY : Source/Actor/Building.i

# target to preprocess a source file
Source/Actor/Building.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Building.cpp.i
.PHONY : Source/Actor/Building.cpp.i

Source/Actor/Building.s: Source/Actor/Building.cpp.s
.PHONY : Source/Actor/Building.s

# target to generate assembly for a file
Source/Actor/Building.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Building.cpp.s
.PHONY : Source/Actor/Building.cpp.s

Source/Actor/Marine.o: Source/Actor/Marine.cpp.o
.PHONY : Source/Actor/Marine.o

# target to build an object file
Source/Actor/Marine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Marine.cpp.o
.PHONY : Source/Actor/Marine.cpp.o

Source/Actor/Marine.i: Source/Actor/Marine.cpp.i
.PHONY : Source/Actor/Marine.i

# target to preprocess a source file
Source/Actor/Marine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Marine.cpp.i
.PHONY : Source/Actor/Marine.cpp.i

Source/Actor/Marine.s: Source/Actor/Marine.cpp.s
.PHONY : Source/Actor/Marine.s

# target to generate assembly for a file
Source/Actor/Marine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Marine.cpp.s
.PHONY : Source/Actor/Marine.cpp.s

Source/Actor/Movement.o: Source/Actor/Movement.cpp.o
.PHONY : Source/Actor/Movement.o

# target to build an object file
Source/Actor/Movement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Movement.cpp.o
.PHONY : Source/Actor/Movement.cpp.o

Source/Actor/Movement.i: Source/Actor/Movement.cpp.i
.PHONY : Source/Actor/Movement.i

# target to preprocess a source file
Source/Actor/Movement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Movement.cpp.i
.PHONY : Source/Actor/Movement.cpp.i

Source/Actor/Movement.s: Source/Actor/Movement.cpp.s
.PHONY : Source/Actor/Movement.s

# target to generate assembly for a file
Source/Actor/Movement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Movement.cpp.s
.PHONY : Source/Actor/Movement.cpp.s

Source/Actor/Tank.o: Source/Actor/Tank.cpp.o
.PHONY : Source/Actor/Tank.o

# target to build an object file
Source/Actor/Tank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Tank.cpp.o
.PHONY : Source/Actor/Tank.cpp.o

Source/Actor/Tank.i: Source/Actor/Tank.cpp.i
.PHONY : Source/Actor/Tank.i

# target to preprocess a source file
Source/Actor/Tank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Tank.cpp.i
.PHONY : Source/Actor/Tank.cpp.i

Source/Actor/Tank.s: Source/Actor/Tank.cpp.s
.PHONY : Source/Actor/Tank.s

# target to generate assembly for a file
Source/Actor/Tank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Tank.cpp.s
.PHONY : Source/Actor/Tank.cpp.s

Source/Actor/Unit.o: Source/Actor/Unit.cpp.o
.PHONY : Source/Actor/Unit.o

# target to build an object file
Source/Actor/Unit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Unit.cpp.o
.PHONY : Source/Actor/Unit.cpp.o

Source/Actor/Unit.i: Source/Actor/Unit.cpp.i
.PHONY : Source/Actor/Unit.i

# target to preprocess a source file
Source/Actor/Unit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Unit.cpp.i
.PHONY : Source/Actor/Unit.cpp.i

Source/Actor/Unit.s: Source/Actor/Unit.cpp.s
.PHONY : Source/Actor/Unit.s

# target to generate assembly for a file
Source/Actor/Unit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Unit.cpp.s
.PHONY : Source/Actor/Unit.cpp.s

Source/Actor/Worker.o: Source/Actor/Worker.cpp.o
.PHONY : Source/Actor/Worker.o

# target to build an object file
Source/Actor/Worker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Worker.cpp.o
.PHONY : Source/Actor/Worker.cpp.o

Source/Actor/Worker.i: Source/Actor/Worker.cpp.i
.PHONY : Source/Actor/Worker.i

# target to preprocess a source file
Source/Actor/Worker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Worker.cpp.i
.PHONY : Source/Actor/Worker.cpp.i

Source/Actor/Worker.s: Source/Actor/Worker.cpp.s
.PHONY : Source/Actor/Worker.s

# target to generate assembly for a file
Source/Actor/Worker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Actor/Worker.cpp.s
.PHONY : Source/Actor/Worker.cpp.s

Source/Camera/Camera.o: Source/Camera/Camera.cpp.o
.PHONY : Source/Camera/Camera.o

# target to build an object file
Source/Camera/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/Camera.cpp.o
.PHONY : Source/Camera/Camera.cpp.o

Source/Camera/Camera.i: Source/Camera/Camera.cpp.i
.PHONY : Source/Camera/Camera.i

# target to preprocess a source file
Source/Camera/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/Camera.cpp.i
.PHONY : Source/Camera/Camera.cpp.i

Source/Camera/Camera.s: Source/Camera/Camera.cpp.s
.PHONY : Source/Camera/Camera.s

# target to generate assembly for a file
Source/Camera/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/Camera.cpp.s
.PHONY : Source/Camera/Camera.cpp.s

Source/Camera/FreeCameraController.o: Source/Camera/FreeCameraController.cpp.o
.PHONY : Source/Camera/FreeCameraController.o

# target to build an object file
Source/Camera/FreeCameraController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/FreeCameraController.cpp.o
.PHONY : Source/Camera/FreeCameraController.cpp.o

Source/Camera/FreeCameraController.i: Source/Camera/FreeCameraController.cpp.i
.PHONY : Source/Camera/FreeCameraController.i

# target to preprocess a source file
Source/Camera/FreeCameraController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/FreeCameraController.cpp.i
.PHONY : Source/Camera/FreeCameraController.cpp.i

Source/Camera/FreeCameraController.s: Source/Camera/FreeCameraController.cpp.s
.PHONY : Source/Camera/FreeCameraController.s

# target to generate assembly for a file
Source/Camera/FreeCameraController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/FreeCameraController.cpp.s
.PHONY : Source/Camera/FreeCameraController.cpp.s

Source/Camera/LockCameraController.o: Source/Camera/LockCameraController.cpp.o
.PHONY : Source/Camera/LockCameraController.o

# target to build an object file
Source/Camera/LockCameraController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/LockCameraController.cpp.o
.PHONY : Source/Camera/LockCameraController.cpp.o

Source/Camera/LockCameraController.i: Source/Camera/LockCameraController.cpp.i
.PHONY : Source/Camera/LockCameraController.i

# target to preprocess a source file
Source/Camera/LockCameraController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/LockCameraController.cpp.i
.PHONY : Source/Camera/LockCameraController.cpp.i

Source/Camera/LockCameraController.s: Source/Camera/LockCameraController.cpp.s
.PHONY : Source/Camera/LockCameraController.s

# target to generate assembly for a file
Source/Camera/LockCameraController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Camera/LockCameraController.cpp.s
.PHONY : Source/Camera/LockCameraController.cpp.s

Source/Framework/Framework.o: Source/Framework/Framework.cpp.o
.PHONY : Source/Framework/Framework.o

# target to build an object file
Source/Framework/Framework.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/Framework.cpp.o
.PHONY : Source/Framework/Framework.cpp.o

Source/Framework/Framework.i: Source/Framework/Framework.cpp.i
.PHONY : Source/Framework/Framework.i

# target to preprocess a source file
Source/Framework/Framework.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/Framework.cpp.i
.PHONY : Source/Framework/Framework.cpp.i

Source/Framework/Framework.s: Source/Framework/Framework.cpp.s
.PHONY : Source/Framework/Framework.s

# target to generate assembly for a file
Source/Framework/Framework.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/Framework.cpp.s
.PHONY : Source/Framework/Framework.cpp.s

Source/Framework/ResourceManager.o: Source/Framework/ResourceManager.cpp.o
.PHONY : Source/Framework/ResourceManager.o

# target to build an object file
Source/Framework/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/ResourceManager.cpp.o
.PHONY : Source/Framework/ResourceManager.cpp.o

Source/Framework/ResourceManager.i: Source/Framework/ResourceManager.cpp.i
.PHONY : Source/Framework/ResourceManager.i

# target to preprocess a source file
Source/Framework/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/ResourceManager.cpp.i
.PHONY : Source/Framework/ResourceManager.cpp.i

Source/Framework/ResourceManager.s: Source/Framework/ResourceManager.cpp.s
.PHONY : Source/Framework/ResourceManager.s

# target to generate assembly for a file
Source/Framework/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/ResourceManager.cpp.s
.PHONY : Source/Framework/ResourceManager.cpp.s

Source/Framework/main.o: Source/Framework/main.cpp.o
.PHONY : Source/Framework/main.o

# target to build an object file
Source/Framework/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/main.cpp.o
.PHONY : Source/Framework/main.cpp.o

Source/Framework/main.i: Source/Framework/main.cpp.i
.PHONY : Source/Framework/main.i

# target to preprocess a source file
Source/Framework/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/main.cpp.i
.PHONY : Source/Framework/main.cpp.i

Source/Framework/main.s: Source/Framework/main.cpp.s
.PHONY : Source/Framework/main.s

# target to generate assembly for a file
Source/Framework/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Framework/main.cpp.s
.PHONY : Source/Framework/main.cpp.s

Source/Graphics/GLTFStaticModel.o: Source/Graphics/GLTFStaticModel.cpp.o
.PHONY : Source/Graphics/GLTFStaticModel.o

# target to build an object file
Source/Graphics/GLTFStaticModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/GLTFStaticModel.cpp.o
.PHONY : Source/Graphics/GLTFStaticModel.cpp.o

Source/Graphics/GLTFStaticModel.i: Source/Graphics/GLTFStaticModel.cpp.i
.PHONY : Source/Graphics/GLTFStaticModel.i

# target to preprocess a source file
Source/Graphics/GLTFStaticModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/GLTFStaticModel.cpp.i
.PHONY : Source/Graphics/GLTFStaticModel.cpp.i

Source/Graphics/GLTFStaticModel.s: Source/Graphics/GLTFStaticModel.cpp.s
.PHONY : Source/Graphics/GLTFStaticModel.s

# target to generate assembly for a file
Source/Graphics/GLTFStaticModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/GLTFStaticModel.cpp.s
.PHONY : Source/Graphics/GLTFStaticModel.cpp.s

Source/Graphics/Graphics.o: Source/Graphics/Graphics.cpp.o
.PHONY : Source/Graphics/Graphics.o

# target to build an object file
Source/Graphics/Graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Graphics.cpp.o
.PHONY : Source/Graphics/Graphics.cpp.o

Source/Graphics/Graphics.i: Source/Graphics/Graphics.cpp.i
.PHONY : Source/Graphics/Graphics.i

# target to preprocess a source file
Source/Graphics/Graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Graphics.cpp.i
.PHONY : Source/Graphics/Graphics.cpp.i

Source/Graphics/Graphics.s: Source/Graphics/Graphics.cpp.s
.PHONY : Source/Graphics/Graphics.s

# target to generate assembly for a file
Source/Graphics/Graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Graphics.cpp.s
.PHONY : Source/Graphics/Graphics.cpp.s

Source/Graphics/Sprite.o: Source/Graphics/Sprite.cpp.o
.PHONY : Source/Graphics/Sprite.o

# target to build an object file
Source/Graphics/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Sprite.cpp.o
.PHONY : Source/Graphics/Sprite.cpp.o

Source/Graphics/Sprite.i: Source/Graphics/Sprite.cpp.i
.PHONY : Source/Graphics/Sprite.i

# target to preprocess a source file
Source/Graphics/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Sprite.cpp.i
.PHONY : Source/Graphics/Sprite.cpp.i

Source/Graphics/Sprite.s: Source/Graphics/Sprite.cpp.s
.PHONY : Source/Graphics/Sprite.s

# target to generate assembly for a file
Source/Graphics/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Sprite.cpp.s
.PHONY : Source/Graphics/Sprite.cpp.s

Source/Graphics/Texture.o: Source/Graphics/Texture.cpp.o
.PHONY : Source/Graphics/Texture.o

# target to build an object file
Source/Graphics/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Texture.cpp.o
.PHONY : Source/Graphics/Texture.cpp.o

Source/Graphics/Texture.i: Source/Graphics/Texture.cpp.i
.PHONY : Source/Graphics/Texture.i

# target to preprocess a source file
Source/Graphics/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Texture.cpp.i
.PHONY : Source/Graphics/Texture.cpp.i

Source/Graphics/Texture.s: Source/Graphics/Texture.cpp.s
.PHONY : Source/Graphics/Texture.s

# target to generate assembly for a file
Source/Graphics/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Graphics/Texture.cpp.s
.PHONY : Source/Graphics/Texture.cpp.s

Source/Player/Enemy.o: Source/Player/Enemy.cpp.o
.PHONY : Source/Player/Enemy.o

# target to build an object file
Source/Player/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Player/Enemy.cpp.o
.PHONY : Source/Player/Enemy.cpp.o

Source/Player/Enemy.i: Source/Player/Enemy.cpp.i
.PHONY : Source/Player/Enemy.i

# target to preprocess a source file
Source/Player/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Player/Enemy.cpp.i
.PHONY : Source/Player/Enemy.cpp.i

Source/Player/Enemy.s: Source/Player/Enemy.cpp.s
.PHONY : Source/Player/Enemy.s

# target to generate assembly for a file
Source/Player/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Player/Enemy.cpp.s
.PHONY : Source/Player/Enemy.cpp.s

Source/Player/Player.o: Source/Player/Player.cpp.o
.PHONY : Source/Player/Player.o

# target to build an object file
Source/Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Player/Player.cpp.o
.PHONY : Source/Player/Player.cpp.o

Source/Player/Player.i: Source/Player/Player.cpp.i
.PHONY : Source/Player/Player.i

# target to preprocess a source file
Source/Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Player/Player.cpp.i
.PHONY : Source/Player/Player.cpp.i

Source/Player/Player.s: Source/Player/Player.cpp.s
.PHONY : Source/Player/Player.s

# target to generate assembly for a file
Source/Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/Player/Player.cpp.s
.PHONY : Source/Player/Player.cpp.s

Source/UI/Button.o: Source/UI/Button.cpp.o
.PHONY : Source/UI/Button.o

# target to build an object file
Source/UI/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Button.cpp.o
.PHONY : Source/UI/Button.cpp.o

Source/UI/Button.i: Source/UI/Button.cpp.i
.PHONY : Source/UI/Button.i

# target to preprocess a source file
Source/UI/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Button.cpp.i
.PHONY : Source/UI/Button.cpp.i

Source/UI/Button.s: Source/UI/Button.cpp.s
.PHONY : Source/UI/Button.s

# target to generate assembly for a file
Source/UI/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Button.cpp.s
.PHONY : Source/UI/Button.cpp.s

Source/UI/Counter.o: Source/UI/Counter.cpp.o
.PHONY : Source/UI/Counter.o

# target to build an object file
Source/UI/Counter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Counter.cpp.o
.PHONY : Source/UI/Counter.cpp.o

Source/UI/Counter.i: Source/UI/Counter.cpp.i
.PHONY : Source/UI/Counter.i

# target to preprocess a source file
Source/UI/Counter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Counter.cpp.i
.PHONY : Source/UI/Counter.cpp.i

Source/UI/Counter.s: Source/UI/Counter.cpp.s
.PHONY : Source/UI/Counter.s

# target to generate assembly for a file
Source/UI/Counter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Counter.cpp.s
.PHONY : Source/UI/Counter.cpp.s

Source/UI/Image.o: Source/UI/Image.cpp.o
.PHONY : Source/UI/Image.o

# target to build an object file
Source/UI/Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Image.cpp.o
.PHONY : Source/UI/Image.cpp.o

Source/UI/Image.i: Source/UI/Image.cpp.i
.PHONY : Source/UI/Image.i

# target to preprocess a source file
Source/UI/Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Image.cpp.i
.PHONY : Source/UI/Image.cpp.i

Source/UI/Image.s: Source/UI/Image.cpp.s
.PHONY : Source/UI/Image.s

# target to generate assembly for a file
Source/UI/Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Image.cpp.s
.PHONY : Source/UI/Image.cpp.s

Source/UI/OverlayComplete.o: Source/UI/OverlayComplete.cpp.o
.PHONY : Source/UI/OverlayComplete.o

# target to build an object file
Source/UI/OverlayComplete.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayComplete.cpp.o
.PHONY : Source/UI/OverlayComplete.cpp.o

Source/UI/OverlayComplete.i: Source/UI/OverlayComplete.cpp.i
.PHONY : Source/UI/OverlayComplete.i

# target to preprocess a source file
Source/UI/OverlayComplete.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayComplete.cpp.i
.PHONY : Source/UI/OverlayComplete.cpp.i

Source/UI/OverlayComplete.s: Source/UI/OverlayComplete.cpp.s
.PHONY : Source/UI/OverlayComplete.s

# target to generate assembly for a file
Source/UI/OverlayComplete.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayComplete.cpp.s
.PHONY : Source/UI/OverlayComplete.cpp.s

Source/UI/OverlayGame.o: Source/UI/OverlayGame.cpp.o
.PHONY : Source/UI/OverlayGame.o

# target to build an object file
Source/UI/OverlayGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayGame.cpp.o
.PHONY : Source/UI/OverlayGame.cpp.o

Source/UI/OverlayGame.i: Source/UI/OverlayGame.cpp.i
.PHONY : Source/UI/OverlayGame.i

# target to preprocess a source file
Source/UI/OverlayGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayGame.cpp.i
.PHONY : Source/UI/OverlayGame.cpp.i

Source/UI/OverlayGame.s: Source/UI/OverlayGame.cpp.s
.PHONY : Source/UI/OverlayGame.s

# target to generate assembly for a file
Source/UI/OverlayGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayGame.cpp.s
.PHONY : Source/UI/OverlayGame.cpp.s

Source/UI/OverlayTitle.o: Source/UI/OverlayTitle.cpp.o
.PHONY : Source/UI/OverlayTitle.o

# target to build an object file
Source/UI/OverlayTitle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayTitle.cpp.o
.PHONY : Source/UI/OverlayTitle.cpp.o

Source/UI/OverlayTitle.i: Source/UI/OverlayTitle.cpp.i
.PHONY : Source/UI/OverlayTitle.i

# target to preprocess a source file
Source/UI/OverlayTitle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayTitle.cpp.i
.PHONY : Source/UI/OverlayTitle.cpp.i

Source/UI/OverlayTitle.s: Source/UI/OverlayTitle.cpp.s
.PHONY : Source/UI/OverlayTitle.s

# target to generate assembly for a file
Source/UI/OverlayTitle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/OverlayTitle.cpp.s
.PHONY : Source/UI/OverlayTitle.cpp.s

Source/UI/Timer.o: Source/UI/Timer.cpp.o
.PHONY : Source/UI/Timer.o

# target to build an object file
Source/UI/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Timer.cpp.o
.PHONY : Source/UI/Timer.cpp.o

Source/UI/Timer.i: Source/UI/Timer.cpp.i
.PHONY : Source/UI/Timer.i

# target to preprocess a source file
Source/UI/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Timer.cpp.i
.PHONY : Source/UI/Timer.cpp.i

Source/UI/Timer.s: Source/UI/Timer.cpp.s
.PHONY : Source/UI/Timer.s

# target to generate assembly for a file
Source/UI/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/Timer.cpp.s
.PHONY : Source/UI/Timer.cpp.s

Source/UI/UI.o: Source/UI/UI.cpp.o
.PHONY : Source/UI/UI.o

# target to build an object file
Source/UI/UI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/UI.cpp.o
.PHONY : Source/UI/UI.cpp.o

Source/UI/UI.i: Source/UI/UI.cpp.i
.PHONY : Source/UI/UI.i

# target to preprocess a source file
Source/UI/UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/UI.cpp.i
.PHONY : Source/UI/UI.cpp.i

Source/UI/UI.s: Source/UI/UI.cpp.s
.PHONY : Source/UI/UI.s

# target to generate assembly for a file
Source/UI/UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Astroworks.dir/build.make CMakeFiles/Astroworks.dir/Source/UI/UI.cpp.s
.PHONY : Source/UI/UI.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Astroworks"
	@echo "... Source/Actor/Actor.o"
	@echo "... Source/Actor/Actor.i"
	@echo "... Source/Actor/Actor.s"
	@echo "... Source/Actor/Alien.o"
	@echo "... Source/Actor/Alien.i"
	@echo "... Source/Actor/Alien.s"
	@echo "... Source/Actor/Building.o"
	@echo "... Source/Actor/Building.i"
	@echo "... Source/Actor/Building.s"
	@echo "... Source/Actor/Marine.o"
	@echo "... Source/Actor/Marine.i"
	@echo "... Source/Actor/Marine.s"
	@echo "... Source/Actor/Movement.o"
	@echo "... Source/Actor/Movement.i"
	@echo "... Source/Actor/Movement.s"
	@echo "... Source/Actor/Tank.o"
	@echo "... Source/Actor/Tank.i"
	@echo "... Source/Actor/Tank.s"
	@echo "... Source/Actor/Unit.o"
	@echo "... Source/Actor/Unit.i"
	@echo "... Source/Actor/Unit.s"
	@echo "... Source/Actor/Worker.o"
	@echo "... Source/Actor/Worker.i"
	@echo "... Source/Actor/Worker.s"
	@echo "... Source/Camera/Camera.o"
	@echo "... Source/Camera/Camera.i"
	@echo "... Source/Camera/Camera.s"
	@echo "... Source/Camera/FreeCameraController.o"
	@echo "... Source/Camera/FreeCameraController.i"
	@echo "... Source/Camera/FreeCameraController.s"
	@echo "... Source/Camera/LockCameraController.o"
	@echo "... Source/Camera/LockCameraController.i"
	@echo "... Source/Camera/LockCameraController.s"
	@echo "... Source/Framework/Framework.o"
	@echo "... Source/Framework/Framework.i"
	@echo "... Source/Framework/Framework.s"
	@echo "... Source/Framework/ResourceManager.o"
	@echo "... Source/Framework/ResourceManager.i"
	@echo "... Source/Framework/ResourceManager.s"
	@echo "... Source/Framework/main.o"
	@echo "... Source/Framework/main.i"
	@echo "... Source/Framework/main.s"
	@echo "... Source/Graphics/GLTFStaticModel.o"
	@echo "... Source/Graphics/GLTFStaticModel.i"
	@echo "... Source/Graphics/GLTFStaticModel.s"
	@echo "... Source/Graphics/Graphics.o"
	@echo "... Source/Graphics/Graphics.i"
	@echo "... Source/Graphics/Graphics.s"
	@echo "... Source/Graphics/Sprite.o"
	@echo "... Source/Graphics/Sprite.i"
	@echo "... Source/Graphics/Sprite.s"
	@echo "... Source/Graphics/Texture.o"
	@echo "... Source/Graphics/Texture.i"
	@echo "... Source/Graphics/Texture.s"
	@echo "... Source/Player/Enemy.o"
	@echo "... Source/Player/Enemy.i"
	@echo "... Source/Player/Enemy.s"
	@echo "... Source/Player/Player.o"
	@echo "... Source/Player/Player.i"
	@echo "... Source/Player/Player.s"
	@echo "... Source/UI/Button.o"
	@echo "... Source/UI/Button.i"
	@echo "... Source/UI/Button.s"
	@echo "... Source/UI/Counter.o"
	@echo "... Source/UI/Counter.i"
	@echo "... Source/UI/Counter.s"
	@echo "... Source/UI/Image.o"
	@echo "... Source/UI/Image.i"
	@echo "... Source/UI/Image.s"
	@echo "... Source/UI/OverlayComplete.o"
	@echo "... Source/UI/OverlayComplete.i"
	@echo "... Source/UI/OverlayComplete.s"
	@echo "... Source/UI/OverlayGame.o"
	@echo "... Source/UI/OverlayGame.i"
	@echo "... Source/UI/OverlayGame.s"
	@echo "... Source/UI/OverlayTitle.o"
	@echo "... Source/UI/OverlayTitle.i"
	@echo "... Source/UI/OverlayTitle.s"
	@echo "... Source/UI/Timer.o"
	@echo "... Source/UI/Timer.i"
	@echo "... Source/UI/Timer.s"
	@echo "... Source/UI/UI.o"
	@echo "... Source/UI/UI.i"
	@echo "... Source/UI/UI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

